import type { MetadataRoute } from "next";
import { cardPages, type CardPage } from "@/lib/cards";
import { getSiteUrl } from "@/lib/site-url";
import { getAllSeoGuides, seoGuidePath } from "@/lib/seo-guides-data";
import { SEO_GUIDE_DEFINITIONS_POKEMON } from "@/lib/seo-guides-data-pokemon";
import { TIER1_SEO_PAGES, tier1Path } from "@/lib/tier1-seo";

/** ISO lastmod for each card; prefers updatedAt, then createdAt. */
function lastModifiedForCard(c: CardPage): Date {
  const u = Date.parse(c.updatedAt);
  if (!Number.isNaN(u)) return new Date(u);
  const cr = Date.parse(c.createdAt);
  if (!Number.isNaN(cr)) return new Date(cr);
  return new Date();
}

/**
 * Every `/cards/[slug]` from static `data/cards.json` (via `cardPages`).
 * Dedupes by slug; stable sort for deterministic XML.
 */
function buildCardRoutes(base: string): MetadataRoute.Sitemap {
  const bySlug = new Map<string, CardPage>();
  for (const c of cardPages) {
    const prev = bySlug.get(c.slug);
    if (!prev || lastModifiedForCard(c) > lastModifiedForCard(prev)) {
      bySlug.set(c.slug, c);
    }
  }
  return Array.from(bySlug.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, c]) => ({
      url: `${base}/cards/${encodeURIComponent(c.slug)}`,
      lastModified: lastModifiedForCard(c),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    }));
}

/**
 * Served at `/sitemap.xml` (Next.js MetadataRoute). Uses getSiteUrl()
 * (NEXT_PUBLIC_APP_URL or https://getcardsnap.com). Valid XML is generated by the framework.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = getSiteUrl();
  const lastModified = new Date();

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${base}/`, lastModified, changeFrequency: "weekly", priority: 1 },
    { url: `${base}/cards`, lastModified, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/guides`, lastModified, changeFrequency: "weekly", priority: 0.85 },
    { url: `${base}/psa-grading-calculator`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/grade-or-skip/baseball`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/grade-or-skip/basketball`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/grade-or-skip/pokemon`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/methodology`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/privacy`, lastModified, changeFrequency: "yearly", priority: 0.4 },
    { url: `${base}/terms`, lastModified, changeFrequency: "yearly", priority: 0.4 },
    { url: `${base}/contact`, lastModified, changeFrequency: "yearly", priority: 0.4 },
  ];

  const pokemonSlugs = new Set(SEO_GUIDE_DEFINITIONS_POKEMON.map((g) => g.slug));

  const seoGuideRoutes: MetadataRoute.Sitemap = getAllSeoGuides()
    .filter((g) => !pokemonSlugs.has(g.slug))
    .map((g) => ({
      url: `${base}${seoGuidePath(g.slug)}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    }));

  const pokemonGuideRoutes: MetadataRoute.Sitemap = SEO_GUIDE_DEFINITIONS_POKEMON.map((g) => ({
    url: `${base}/should-i-grade-pokemon/${g.slug}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.8,
  }));

  const cardRoutes = buildCardRoutes(base);

  const tier1ProgrammaticRoutes: MetadataRoute.Sitemap = TIER1_SEO_PAGES.map(
    (e) => ({
      url: `${base}${tier1Path(e.template, e.cardSlug)}`,
      lastModified,
      changeFrequency: "weekly" as const,
      priority: 0.85,
    })
  );

  return [
    ...staticRoutes,
    ...seoGuideRoutes,
    ...pokemonGuideRoutes,
    ...cardRoutes,
    ...tier1ProgrammaticRoutes,
  ];
}
